# Travis CI configuration

language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

install:
  - composer install

script:
  - phpunit
